global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.rules"

scrape_configs:
  - job_name: fmq
    metrics_path: /metrics
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets:
        - host.docker.internal:8080
