{
 "title": "FMQ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"fmq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"fmq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_threads{job=\"fmq\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}